# Programming for Data Analysis Assignment 2019

The assignment concerns the `numpy.random` package in Python.
Explain the use of the package including detailed explanations of at least five of the distributions provided for in the package.
There are four distinct task to be carried out in the Jupyter Notebook.
1. Explain the overall purpose of the package.
2. Explain the use of the “Simple random data” and “Permutations” functions. 
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers.
***

<a id='toc'></a>
# Table of contents

## Project Tasks

1. [ Explain the overall purpose of the package](#task1)
2. [Explain the use of the Simple random data and Permutations functions.](#task2)
    - 2.1 [Simple random data functions](#task2.1)
    - 2.2 [Permutations Functions](#task2.2)
3. [Explain the use and purpose of at least five “Distributions” functions](#task3)
4. [Explain the use of seeds in generating pseudorandom numbers](#task4)
5. [References](#references)
  
***

## Python and other software tools used in this project

### How to download this repository
Go to the URL for the repository on GitHub at https://github.com/angela1C/numpy.random.git.
Click the green Clone or download button


### Python 3

### Jupyter notebook

### NumPy package

### Package and documentation versions.
Version 1.16.2 is the version of NumPy that I am working with so the documentation I am referring to is the [NumPy Reference 1.16](https://numpy.org/doc/1.16/reference/index.html#numpy-reference) manual. This details functions, modules, and objects included in NumPy, describing what they are and what they do. It contains detailed reference documentation of the functions and classes contained in the NumPy package. 

***

### Jupyter notebook settings
In order to get the output of multiple python statements to print, instead of just the last statement in a cell, you can change the settings as per the [jupyter notebook tips, tricks and shortcuts blogpost by dataquest](https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/)

<a id='libraries'></a>
### Import python libraries

In [2]:

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
#np.version.version  # check what version of numpy and other packages I have installed.
np.__version__  # '1.16.2'
pd.__version__
sns.__version__

<a id='notes'></a>


### some quick notes here - remove this later!
- what is the stated aim of the package?
- why would you want to generate random numbers?
- pythons built-in `random` module can also generate random numbers so what is the difference.
- how are random numbers generated using pseudo random number generator  
- use plots to illustrate the difference between different probability distributions. 

The aim of the assignment is to be able to give a good overview of the numpy.random functions in your own words without rehashing the documentation. All of the functions return random value or values in some shape or form. 

I will go down through the simple random data functions and see how they differ from one another. A first glance at the functions in the documentation show that four of the functions return similar output. 
These are the following four functions which all return random floats in the half-open interval `[0.0,1.0)`

- `random_sample([size])` returns random floats in the half-open interval `[0.0, 1.0)`  
- `random([size])` also returns random floats in the half-open interval` [0.0, 1.0)`.
- `ranf([size])` again returns random floats in the half-open interval `[0.0, 1.0)`.
- `sample([size])` returns random floats in the half-open interval `[0.0, 1.0)`.

I will look at these together and see how they differ. `random.randint` and `random.random_integer` also look quite similar. 

I first went through some of the functions for task 2 but having done that I am going to reduce some of the clutter there and integrate it somehow with task 3 related to distributions as they are very much related. Its just the way the documentation is laid out. Rather than going through the simple random data functions I will look at the simple random data functions for each of the distributions covered which seem to be just the uniform distribution and the normal and standard normal distributions.

[Back to top](#toc)

## Random numbers in Python

<a id='task1'></a>
# 1. Explain the overall purpose of the package numpy.random


## NumPy's Random module

**numpy.random** is a sub-package or module of the NumPy package that generates random numbers. [what is NumPy](https://docs.scipy.org/doc/numpy/user/whatisnumpy.html) in the **Scipy** documentation gives a good overview of what exactly the **NumPy** package itself is for.


According to [wolfram mathworld](http://mathworld.wolfram.com/RandomNumber.html)a **random number** 
>is a number chosen as if by chance from some specified distribution such that selection of a large set of these numbers reproduces the underlying distribution. Almost always, such numbers are also required to be independent, so that there are no correlations between successive numbers. Computer-generated random numbers are sometimes called pseudorandom numbers, while the term "random" is reserved for the output of unpredictable physical processes. When used without qualification, the word "random" usually means "random with a uniform distribution." Other distributions are of course possible.








**NumPy**, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python and many other packages that are used for data analytics and machine learning are built on NumPy. 
NumPy's main data structure is the **ndarray**. This is a homogenuous multidimensional array which is also known by the alias **array**. Python itself does not have an array data structure so NumPy allow for the creation and manipulatation of arrays of numbers. Python's own matrix operations are quite inefficient when compared to NumPy's capabilities on large multi-dimensional arrays of numbers and such matrix type operations are very commonly used when analysing data and for other computing purposes.

A NumPy array resembles a table of elements that are all of the same type. The elements which are usually numbers are indexed by a tuple of positive integers. Axes refer to the dimensions of a NumPy array.
The NumPy package has many mathematical functions and algorithms for doing very fast numerical operations on arrays.

Batch operations avoid the need to use loops by working on entire arrays of data at a time using **vectorisation** but using similar syntax to working with scalars.

NumPy can also be used to simulate data. While csv data is commonly imported into NumPy for analysis (or into a package such as pandas that uses NumPy), it is often useful to be able to simulate data to analyse before the real data may be collected or available. 
  
A NumPy **ndarray** can be created using the Numpy `array` function which takes any sequence-like objects such as lists, nested lists etc but there are other NumPy functions that also create new arrays such as `zeros`, `ones`, `empty`, `arange`, `full` and `eye` among others as detailed in the [numpy quickstart tutorial](https://numpy.org/devdocs/user/quickstart.html). NumPy's random module also creates ndarray objects (or scalars).

Some key points about any of NumPy's ndarray objects include:
- The data in an *ndarray* must be homogeneous, that is all of it's data elements must of the same type.
- Arrays have a *ndim* attribute for the number of axes or dimensions of the array
- Arrays have a *shape* attribute which is a tuple that indicates the size of the array in each dimension.
The length of the *shape* tupple is the number of axes that the array has. 
- Arrays have a *dtype* attribute which is an object that describes the data type of the array.
- The `size` attribute is the total number of elements in the array.


## NumPy's Random module 
Python has a built-in [random](https://docs.python.org/3/library/random.html) module that provides a number of tools for working with random numbers. However this `random` module only generates or samples one value at a time.  Loops or iteration are used for working with sequences of random numbers while on the other hand the `numpy.random` module provides functions that can efficiently generate arrays of sample values from various probability distributions rather than one value at a time. NumPy's random module is much much faster and more efficient than python's random module for this purpose particularly when working with larger arrays.
NumPy's random module is used more for generating random series of data rather than the scalar values generated by the python random module whereas the random module is sufficient for other purposes??

The `numpy.random` package uses NumPy's key data structure - the multi-dimensional `ndarray` arrays. Given an input array of elements, random functions will allow you to select a random sample of elements from the array or generate sequences.


Both Python's random and NumPy random packages generate pseudorandom numbers rather than actual random numbers. 
Actual random numbers cannot be generated by software applications. Both `random` modules implements **pseudorandom** numbers for various distributions. 
Python uses the **Mersenne Twister** as the core generator. The Mersenne Twister is one of the most extensively tested random number generators in existence. According to [wikipedia](https://en.m.wikipedia.org/wiki/Mersenne_Twister), the Mersenne Twister is by far the most widely used general-purpose pseudorandom number generator PRNG whose name derives from the fact that its period length is chosen to be a Mersenne prime (a prime number that is one less than a power of two. That is, it is a prime number of the form Mn = 2n − 1 for some integer n.).




### Generating random numbers  
[Back to top](#toc)  
  

*Random* numbers generated by either the built-in python `random` module or the `numpy.random` package or any other computer software application are not actually random at all but **pseudo-random** numbers. While they may appear random they are actually predetermined. Python's random package and numpy.random are pseudo-random number generators.

In general, any computer program only produce outputs based on inputs and according to a set of predetermined steps or rules so therefore it would not be possible for a computer to generate truly random numbers. Computer software only generate sequences that look like random numbers in that you could not predict the next number generated unless you had a 
key piece of information which is called the **seed**. If you know this **seed** then you can predict the next number to be generated in a sequence and therefore the numbers generated are not actually random as such. A true random number generator would involve **hardware** while a computer program can only generate psuedo-random numbers.

The random numbers are generated are in a sequence according to some **deterministic algorithm** from an input called a **seed** and therefore do not actually contain any randomness at all. The random numbers output are based on predetermined rules. This means that the outputs can be repeated by following the same set of steps and given the same inputs.

The **seed** used is typically the time (to the microsecond) on the computer when the code was run. To recreate the exact same sequence of random numbers, then you can just explicitly supply the seed as an input to the random number generator.
Without supplying a seed yourself explicitly, the current system time in milliseconds is used as the seed

The sequence of numbers generated may have properties of randomness and look random but there is an important distinction between random and pseudorandom numbers. Pseudorandom number generators should never be used for cryptographic purposes because the predictability could be used to break the encryption.

See [Section 4](#task4) for more detail relating to task 4. **Explain the use of seeds in generating pseudorandom numbers.**
  
You may want to generate the exact same sequence of numbers for testing or reproducibility. It is easier to share code that can be exactly reproduced by someone else to get the exact same results.


## Why generate random numbers?

[Back to top](#toc)  
The numpy.random package is used to generate random numbers (or pseudo random numbers) so I guess the question first is why would you want to generate random numbers!

Being able to randomly select elements has many uses in computer applications such as gaming. 
The ability to generate sets of numbers from a particular probability distribution is also very useful for simulating a dataset, maybe in the absence of an actual dataset or for demonstrating or learning statistical and analytical concepts. Statistics and probability involve the concept of randomness and uncertainty.

Data Analytics and Machine learning projects frequently rely on random samples of a datasets for testing and evaluation purposes. Often a dataset is split into training and test set where the dataset is shuffled and a classifier is built with a randomly selected subset of the dataset and the classifier is then tested on the remaining subset of the data. 
This allows you to evaluate the accuracy of the classifier before applying it to new observations as otherwise you would not know if the classifier was any good or not.

There are many computational and statistical methods that use random numbers and random sampling. 

I think that some clustering algorithms often use random starting point. will come back to this.
[Back to top](#toc)

<a id='task2'></a>
# 2. Explain the use of the “Simple random data” and “Permutations” functions.
[Back to top](#toc)

The simple random data functions listed under the [Random Sampling using numpy.random](https://docs.scipy.org/doc/numpy-1.16.1/reference/routines.random.html#random-sampling-numpy-random.) of the NumPy documentation mostly return random values in a given shape.

<a id='Simplerandomdata'></a>
### Simple random data
- `rand(d0, d1, …, dn)`	Random values in a given shape.
- `randn(d0, d1, …, dn)`	Return a sample (or samples) from the “standard normal” distribution.
- `randint(low[, high, size, dtype])`	Return random integers from low (inclusive) to high (exclusive).
- `random_integers(low[, high, size])`	Random integers of type np.int between low and high, inclusive.
- `random_sample([size])`	Return random floats in the half-open interval `[0.0, 1.0)`.
- `random([size])`	Return random floats in the half-open interval `[0.0, 1.0)`.
- `ranf([size])`	Return random floats in the half-open interval `[0.0, 1.0)`.
- `sample([size])`	Return random floats in the half-open interval `[0.0, 1.0)`.
- `choice(a[, size, replace, p])`	Generates a random sample from a given 1-D array
- `bytes(length)`	Return random bytes.

This section is closely linked to section on [Distributions](#distributions) which are used to draw samples from various probability distributions.

<a id='task2.1'></a>
## 2.1 Simple random data functions
[Back to top](#toc)


<img src="/Simple_random_data.png" width="400" alt="Simple random data" />

[import libraries](#libraries)

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

***
## Random Floats from the Standard Normal Distribution

The **`numpy.random.randn()`** function will return a sample (or samples) of random values from the **standard normal distribution** which has a mean 0 and a standard deviation of 1. The standard normal distribution is also known as the Gaussian distribution.
This function returns either a single value or a numpy array containing random floats sampled from a univariate “normal” distribution of mean 0 and variance 1.

The dimensions of the resulting array depends on the arguments passed to the function.  A single float randomly sampled from the distribution is returned if no argument is provided. 
>A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution, or a single such float if no parameters were supplied.

The **`numpy.random.randn()`** function is related to **`numpy.random.standard_normal`** function which is used to draw
samples from a **Standard Normal distribution** (mean=0, stdev=1). 
`numpy.random.randn()` is actually a convenience function for `numpy.random.standard_normal`. It returns a single float or an ndarray of floats.

You can get random samples from $N(\mu, \sigma^2)$ by scaling the values. This is done by multiplying the values by $\sigma$ and adding $\mu$. 
***

- `numpy.random.standard_normal`  takes an optional size parameter which can be an integer or a tuple of integers. Otherwise a single value is returned. If a tuple of integers is provided then this determines the shape of the resulting array and the number of elements in the array. 

>(Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn.)

>You can get random samples from $N(\mu, \sigma^2)$ by scaling the values. This is done by multiplying the values by $\sigma$ (the standard deviation) and adding $\mu$ (the mean). 

>sigma * np.random.randn(...) + mu.

I will go into this more in the section about probability distributions.
see [numpy.random.standard_normal](#standard_normal) distribution function.

Here I will create various sized arrays using `numpy.random.randn` function.
If no argument is provided then a single float value is returned. The arguments can only be positive integers.
If two arguments are provided then the returned ndarray will have two dimensions. The number of elements in the array will be the product of these two values.

I have written a small function below to print the array attributes rather than repeating myself over and over!
I will use my function `arrayinfo` to print the resulting arrays with their dimensions.


In [3]:
def arrayinfo(myarray):  # pass the array to the function to print the attributes
    """print the attributes of the numpy array passed to this function"""
    
    print(f"\n This array is a {myarray.ndim} dimensional array, with a{myarray.shape} shape and the array has a total number of {myarray.size} {myarray.dtype} elements")
    #print(f"\n This array has a mean of {np.mean(myarray)} and standard deviation of {np.std(myarray)}")
    return myarray


In [73]:
 # creates a one dimensional array of 10 values
arrayinfo(np.random.randn(10))
arrayinfo(np.random.randn(3,2)) # a 3 by 2 array of samples from standard normal distribution. This will have 3 times 2 value
arrayinfo(np.random.randn(5,3))# a 5 by 3 array with 15 values
arrayinfo(np.random.randn(2,2,2)) # a 3D array containing 2*2*2 = 8 values
arrayinfo(np.random.randn(2,2,2,2)) # a 4D array containing 2*2*2*2 = 16 values



 This array is a 1 dimensional array, with a(10,) shape and the array has a total number of 10 float64 elements


array([ 1.683832  ,  0.96450875,  0.70007193,  1.18497957,  0.08389364,
       -0.7094674 , -1.21896654, -0.14652673, -1.01849136, -0.05836458])


 This array is a 2 dimensional array, with a(3, 2) shape and the array has a total number of 6 float64 elements


array([[-2.02564567,  0.98082484],
       [ 0.24219407,  0.33176385],
       [ 1.26450988, -0.93424381]])


 This array is a 2 dimensional array, with a(5, 3) shape and the array has a total number of 15 float64 elements


array([[ 0.27835135,  0.73166779,  0.46670426],
       [-1.38691501, -0.29130416,  1.67422586],
       [-0.66310306,  0.39300962, -0.24523913],
       [ 1.09622297, -0.22156643,  0.66545255],
       [ 0.79274018, -0.71973844, -0.20287568]])


 This array is a 3 dimensional array, with a(2, 2, 2) shape and the array has a total number of 8 float64 elements


array([[[-0.62321908,  1.39145932],
        [-1.3357354 ,  1.1866396 ]],

       [[-1.00645172,  1.26556461],
        [ 0.59245069,  1.21443537]]])


 This array is a 4 dimensional array, with a(2, 2, 2, 2) shape and the array has a total number of 16 float64 elements


array([[[[-0.25977826, -0.1188614 ],
         [ 0.13548862,  0.312284  ]],

        [[ 2.37726015,  2.90273462],
         [-0.15723812, -0.54738732]]],


       [[[-0.37994496,  0.25849004],
         [-0.57154598, -0.15430268]],

        [[-1.28067137,  0.87188146],
         [-0.05618031,  0.97926138]]]])

### For random samples from $N(\mu, \sigma^2)$
You can get random samples from $N(\mu, \sigma^2)$ by scaling the values. This is done by multiplying the values by $\sigma$ and adding $\mu$. 

In [59]:
# Two-by-four array of samples from N(3, 6.25):

2.5 * np.random.randn(2, 50) + 3

array([[ 1.20538406,  0.97182687,  3.63913998, -2.46409465,  4.88903094,
         2.73033967,  1.19853186, -0.0419711 ,  1.42065664,  0.79388019,
         2.94286584,  7.88975172,  1.80353008, -0.84654436,  7.34185877,
         6.0464988 ,  3.05555197,  6.01649458,  1.86680697,  7.42382942,
         0.38188608,  7.23183948,  4.6766763 ,  3.99380664,  2.54247518,
        -1.06098358,  7.8055642 ,  9.60151305,  5.78663115,  7.3291816 ,
         4.64837314, -1.7670694 ,  0.86891823,  6.30770056,  2.82085422,
        -1.31396788,  6.88225158,  2.21037416,  3.30452881,  4.78598612,
         5.00601183,  1.27227906,  0.30494326,  7.5884345 ,  4.99962811,
         0.99817107,  9.89357673,  0.92514042, -0.26929369,  2.82066323],
       [ 0.80258182,  4.17177079,  4.99127707,  4.07439767,  6.57247742,
         5.50483072, -1.6320006 ,  2.3255545 ,  1.44381083,  3.7019217 ,
         2.36373913, -0.08834819,  2.41057214,  5.32972346,  4.5703619 ,
         3.7724463 ,  5.03796168,  2.33828963, -1.

In [47]:
np.sqrt(6.25)

2.5

In [64]:
x = 2.5 * np.random.randn(20, 1000) + 3

print(f" This array is a {x.ndim} dimensional array with {x.size} elements, has a mean of {np.mean(x)} and standard deviation of {np.std(x)}")
x = 2.5 * np.random.randn(20, 10000) + 3

print(f" This array is a {x.ndim} dimensional array with {x.size} elements, has a mean of {np.mean(x)} and standard deviation of {np.std(x)}")

 This array is a 2 dimensional array with 20000 elements, has a mean of 2.9941465809083967 and standard deviation of 2.5197845037844697
 This array is a 2 dimensional array with 200000 elements, has a mean of 3.005816083728727 and standard deviation of 2.5007989828819346


In [7]:
np.random.standard_normal()
np.random.standard_normal(3)
# Unlike` numpy.random.randn()`, to get an array of random values rather than a single value, you need to provide a tuple.
np.random.standard_normal((3,2))

0.3637369971220134

array([-0.07062066, -0.44169168,  0.12012795])

array([[-0.45765562, -0.70456646],
       [ 1.15476696, -1.30999215],
       [ 0.4032045 ,  0.42260935]])

The Python standard library `random` package has a `gauss()` function which is used to sample random floats from a gaussian distribution. Unlike the `numpy.random.randn()` or `numpy.numpy.random.standard_normal` you do need to supply the parameters here for the mean and the standard deviation of the distribution from which the random values will be drawn. Here I use a loop to generate the sequence of random numbers, unlike numpy.random function which is a one liner. 

In [72]:

import random # import random module from python standard library
myseq =[] # create an empty list
for i in range(10):  ## use a loop to generate a sequence of random numbers
    random_gauss = random.gauss(0,1) # mean is 0, standard deviation is 10
    myseq.append(random_gauss)
print(*myseq, sep = ",") # print elements of the list without the brackets

random.gauss(1,3)
random.gauss(0,1)

0.17391144677469975,0.5162322950967666,0.2242250934464846,-1.2862288443233552,1.6153543302956288,-0.3168274158763256,-1.046780629699248,2.415001436132016,-0.2073456988600854,-0.7235638871580158


-0.36102964233974166

1.5443916536272668

In [ ]:
d

In [ ]:
a

In [ ]:
b

[Back to top](#toc)

***
## Random Floating Numbers from the Uniform Distribution

## 1. **The `numpy.random.rand` function**
[numpy.random.rand(d0, d1, ..., dn)](https://numpy.org/doc/1.16/reference/generated/numpy.random.rand.html#numpy-random-rand) creates an array of random samples from a uniform distribution over `[0, 1)`. 

`numpy.random.rand` returns an array of floating point values or a single random value from a **uniform distribution** in the half-open interval `[0,1.)` The values returned can be any number from 0.0 up to 1 but not including 1. 

To use this function you can simply pass positive integer(s) as arguments which determine the dimensions of the array. Without passing any arguments a single float is returned. (Used like this `numpy.random.rand` would be similar to the `random` function in the python **random** standard library which also generates a single random value in the range between 0 and 1.).
  
The size and shape of the returned array will depend on the arguments provided. If you supply just a single integer as an argument, then the array that is returned is a 1 one-dimensional array containing a scalar. The shape is a tuple that shows the size of each dimension of the array.

This function returns an array and as with numpy arrays in general, every row has the same number of elements and every columns has the same number of elements. There can be different number of rows as columns.

I will also look at the following numpy.random simple random data functions which may be related. They all appear to return random floats in the half open interval between 0 and 1.

- `random_sample([size])`	Return random floats in the half-open interval `[0.0, 1.0)`.
- `random([size])`	Return random floats in the half-open interval `[0.0, 1.0)`.
- `ranf([size])`	Return random floats in the half-open interval `[0.0, 1.0)`.
- `sample([size])`	Return random floats in the half-open interval `[0.0, 1.0)`.

In [68]:
# Function to print the array and its attibutes
def arrayinfo(myarray):  # pass the array to the function to print the attributes
    """print the attributes of the numpy array passed to this function"""

    print(f"This array is a {myarray.ndim} dimensional array, with a{myarray.shape} shape and the array has a total number of {myarray.size}  {myarray.dtype} elements\n")
    return myarray




In [69]:
import numpy as np
arrayinfo(np.random.rand(4,1,2))

This array is a 3 dimensional array, with a(4, 1, 2) shape and the array has a total number of 8  float64 elements



array([[[0.36113925, 0.61719078]],

       [[0.09252009, 0.64148724]],

       [[0.78852529, 0.37919272]],

       [[0.42866044, 0.20790093]]])

x = np.random.rand(10) # create a 1-dimensional array with 10 elements from uniform distribution
arrayinfo(x)

In [75]:
np.random.rand.__name__

'rand'

In [71]:
x = np.random.rand(1)  # a single array with 1 element
arrayinfo(x)

x = np.random.rand(3)  # a single array with 3 elements
arrayinfo(x)

x =np.random.rand(3,2) ## array with 3 rows and 2 columns so 3 times 2 = 6 elements
arrayinfo(x)

#Next we can create an array (the outer []) which contains  3 inner arrays where each of these 3 arrays have 2 elements.
#The number of elements is the 6 (3 times 2)

x =np.random.rand(1,2,3)  # a 3 dimensional array 
arrayinfo(x)

x =np.random.rand(4,1,2) # a 3 dimensional array 
arrayinfo(x)

x =np.random.rand(1,2,3,4) # a 4 dimensional array 
arrayinfo(x)

np.random.rand()  ## without any arguments, a scalar is returned



This array is a 1 dimensional array, with a(1,) shape and the array has a total number of 1  float64 elements



array([0.73542615])

This array is a 1 dimensional array, with a(3,) shape and the array has a total number of 3  float64 elements



array([0.85754186, 0.75773242, 0.20517989])

This array is a 2 dimensional array, with a(3, 2) shape and the array has a total number of 6  float64 elements



array([[0.29090766, 0.9112484 ],
       [0.24083928, 0.26425324],
       [0.80438679, 0.66809417]])

This array is a 3 dimensional array, with a(1, 2, 3) shape and the array has a total number of 6  float64 elements



array([[[0.76667273, 0.65476172, 0.77970685],
        [0.04449547, 0.2876642 , 0.16208358]]])

This array is a 3 dimensional array, with a(4, 1, 2) shape and the array has a total number of 8  float64 elements



array([[[0.37454542, 0.26428299]],

       [[0.56756693, 0.7942294 ]],

       [[0.0303302 , 0.09741886]],

       [[0.90221041, 0.11498758]]])

This array is a 4 dimensional array, with a(1, 2, 3, 4) shape and the array has a total number of 24  float64 elements



array([[[[0.62892447, 0.17987898, 0.74211346, 0.06379851],
         [0.54405863, 0.93894094, 0.18607318, 0.27873587],
         [0.18015633, 0.5751779 , 0.53557951, 0.17867641]],

        [[0.60205238, 0.08292474, 0.90688533, 0.57607528],
         [0.89317776, 0.84531747, 0.21520302, 0.95696569],
         [0.03328615, 0.62947675, 0.4355222 , 0.19890095]]]])

0.6819705659878763

#### comparing to the random module of python

In [57]:
import random

for i in range(5):  ## use a loop to generate a sequence of random numbers
    random_number = random.random()
    print(random_number)

0.308047739745292
0.6621644180178464
0.840559759838484
0.7685431771778543
0.5657217173581761


***
## The `numpy.random.random_sample()` function and other similar functions
- `numpy.random.random()`  
- `numpy.random.ranf()` and 
- `numpy.random.sample()`


## the numpy random.random function.

This function returns random floats from the **continuous uniform** distribution in the half-open interval between 0.0 and 1.0 as do the other 3 functions listed here.
The inputs and outputs to the functions appear to be the very same and the examples in the numpy documentation use the `numpy.random.random_sample` function in all cases!

#### `numpy.random.random(size=None)` return random floats in the half-open interval `[0.0, 1.0`).

Results are from the “continuous uniform” distribution over the stated interval. To sample `Unif[a, b)`, b > a multiply the output of random_sample by (b-a) and add a:  `(b - a) * random_sample() + a`
Parameters:
size : int or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
Returns:	 out : float or ndarray of floats
Array of random floats of shape size (unless size=None, in which case a single float is returned).


#### `numpy.random.random_sample(size=None)` returns random floats in the half-open interval `[0.0, 1.0)`.

Results are from the “continuous uniform” distribution over the stated interval. To sample Unif`[a, b)`, b > a multiply the output of random_sample by (b-a) and add a:  `(b - a) * random_sample() + a`
Parameters:	
size : int or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
Returns:	out : float or ndarray of floats
Array of random floats of shape size (unless size=None, in which case a single float is returned).


#### `numpy.random.ranf(size=None)` returns random floats in the half-open interval `[0.0, 1.0)`.

Results are from the “continuous uniform” distribution over the stated interval. To sample Unif`[a, b)`, b > a multiply the output of random_sample by (b-a) and add a:   `(b - a) * random_sample() + a`
Parameters:	size : int or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
Returns:	out : float or ndarray of floats

#### `numpy.random.sample(size=None)` returns random floats in the half-open interval [0.0, 1.0).

Results are from the “continuous uniform” distribution over the stated interval. To sample Unif`[a, b)`, b > a multiply the output of random_sample by (b-a) and add a: `(b - a) * random_sample() + a`
Parameters:	size : int or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
Returns:	out : float or ndarray of floats
Array of random floats of shape size (unless size=None, in which case a single float is returned).



Below I look at these four numpy.random functions which seem to return the same type of results when giving the same arguments for the size parameters.
Note that as yet I am not using the random seed so the actual numbers returned should not be the same.





In [82]:
size =10
np.random.random_sample([size]) # Return random floats in the half-open interval `[0.0, 1.0)`.
np.random.random([size]) # Return random floats in the half-open interval `[0.0, 1.0)`.
np.random.ranf([size]) # return random floats in the half-open interval `[0.0, 1.0)`.
np.random.sample([size]) # Return random floats in the half-open interval `[0.0, 1.0)`.

array([0.87737472, 0.92674473, 0.33227152, 0.5750703 , 0.60090098,
       0.56609338, 0.48790746, 0.56816893, 0.978668  , 0.10567296])

array([0.44121396, 0.38009317, 0.46201773, 0.77366717, 0.17198255,
       0.16106204, 0.25515265, 0.74875129, 0.34504635, 0.27775056])

array([0.37035793, 0.29810289, 0.06557281, 0.26907255, 0.25502794,
       0.23908356, 0.67556454, 0.75308004, 0.69268702, 0.17388944])

array([0.327899  , 0.45573872, 0.56213799, 0.65545784, 0.12165437,
       0.83253703, 0.73226256, 0.83982593, 0.25183539, 0.13934517])

In [84]:
arrayinfo(np.random.random_sample([size]))
arrayinfo(np.random.random([size]))
arrayinfo(np.random.ranf([size]))
arrayinfo(np.random.sample([size]))


 This array is a 1 dimensional array, with a(10,) shape and the array has a total number of 10 float64 elements


array([0.69366089, 0.201972  , 0.74042215, 0.56551507, 0.55615109,
       0.08499656, 0.51405247, 0.99601587, 0.28141893, 0.99755726])


 This array is a 1 dimensional array, with a(10,) shape and the array has a total number of 10 float64 elements


array([0.4275802 , 0.14303059, 0.72002172, 0.51719601, 0.58538403,
       0.08663535, 0.93161721, 0.91834943, 0.41810728, 0.60859324])


 This array is a 1 dimensional array, with a(10,) shape and the array has a total number of 10 float64 elements


array([0.80518543, 0.55175411, 0.39930368, 0.42602508, 0.67640477,
       0.23276812, 0.58438912, 0.11229692, 0.34312615, 0.17776643])


 This array is a 1 dimensional array, with a(10,) shape and the array has a total number of 10 float64 elements


array([0.87483748, 0.75350723, 0.66462001, 0.61430993, 0.20499792,
       0.95824456, 0.84830441, 0.12874189, 0.57768184, 0.21840884])

In [93]:
size =(2,3)
arrayinfo(np.random.random_sample(size))
arrayinfo(np.random.random(size))
arrayinfo(np.random.ranf(size))
arrayinfo(np.random.sample(size))


 This array is a 2 dimensional array, with a(2, 3) shape and the array has a total number of 6 float64 elements


array([[0.92697824, 0.77270703, 0.55279422],
       [0.26481879, 0.97648338, 0.85066673]])


 This array is a 2 dimensional array, with a(2, 3) shape and the array has a total number of 6 float64 elements


array([[0.15827641, 0.47635795, 0.27032424],
       [0.53525217, 0.75148722, 0.93443919]])


 This array is a 2 dimensional array, with a(2, 3) shape and the array has a total number of 6 float64 elements


array([[0.13897994, 0.4292272 , 0.22982672],
       [0.09333337, 0.96161754, 0.741264  ]])


 This array is a 2 dimensional array, with a(2, 3) shape and the array has a total number of 6 float64 elements


array([[0.6282697 , 0.35531365, 0.69283087],
       [0.9733888 , 0.12679387, 0.60351671]])

In [91]:
size
np.random.random_sample(size)

(4, 4, 4)

array([[[0.96559386, 0.63505512, 0.54343061, 0.20193472],
        [0.82042268, 0.7335767 , 0.84328218, 0.35033057],
        [0.32933688, 0.63550001, 0.29394499, 0.94578074],
        [0.30735139, 0.71617941, 0.75724245, 0.82334362]],

       [[0.93968607, 0.89570197, 0.90509749, 0.25455194],
        [0.58784125, 0.22447592, 0.01029788, 0.036407  ],
        [0.6313991 , 0.58479736, 0.65983788, 0.16629075],
        [0.89176259, 0.43059759, 0.82737551, 0.65829151]],

       [[0.64335479, 0.21356419, 0.86059729, 0.89968911],
        [0.66327719, 0.65034601, 0.76415234, 0.71026874],
        [0.12013611, 0.16334905, 0.31996715, 0.10949235],
        [0.62680366, 0.27757363, 0.71161588, 0.32209552]],

       [[0.13265341, 0.72488728, 0.97231035, 0.43588532],
        [0.00168236, 0.10477948, 0.4302954 , 0.73900018],
        [0.09485743, 0.88161615, 0.55053831, 0.15634166],
        [0.09358675, 0.82954577, 0.43227904, 0.94844359]]])

 ### To sample $Unif[a, b), b > a$ 
 multiply the output of random_sample by $(b-a)$ and add a:  `(b - a) * random_sample() + a`
 
 For example, to get a 3 by 2 array of random numbers from the uniform distribution over the interval $[-5, 0)$
 use `5 * np.random.random_sample((3, 2)) - 5`

In [98]:
np.random.seed(0)
5 * np.random.random_sample((3, 2)) - 5
np.random.seed(0)
5 * np.random.random((3, 2)) - 5
np.random.seed(0)
5 * np.random.ranf((3, 2)) - 5
np.random.seed(0)
5 * np.random.sample((3, 2)) - 5


array([[-2.25593248, -1.42405317],
       [-1.98618312, -2.27558409],
       [-2.881726  , -1.77052943]])

array([[-2.25593248, -1.42405317],
       [-1.98618312, -2.27558409],
       [-2.881726  , -1.77052943]])

array([[-2.25593248, -1.42405317],
       [-1.98618312, -2.27558409],
       [-2.881726  , -1.77052943]])

array([[-2.25593248, -1.42405317],
       [-1.98618312, -2.27558409],
       [-2.881726  , -1.77052943]])

The four functions `np.random.random_sample`, `np.random.random`, `np.random.ranf` and `np.random.sample` seem to return the exact same thing when using the same size arguments and intervals. This is shown using the numpy.random.seed function. 

In [ ]:
np.random.random_sample((5,)) # returns 5 values in the half open interval `[0.0,1.0]`
np.random.random((5,))
np.random.ranf((5,))
np.random.sample((5,))

In [ ]:
np.random.random_sample((5,2)) # returns a 5-by-2 array in the half open interval `[0.0,1.0]`
np.random.random((5,2))
np.random.ranf((5,2))
np.random.sample((5,2))

In [ ]:
4 * np.random.random_sample((3, 2)) - 4 # returns a 3-by-2 array of random numbers from [-4, 0). 
4 * np.random.random((3, 2)) - 4 # returns a 3-by-2 array of random numbers from [-4, 0). 
4 * np.random.ranf((3, 2)) - 4 # returns a 3-by-2 array of random numbers from [-4, 0). 
4 * np.random.sample((3, 2)) - 4 # returns a 3-by-2 array of random numbers from [-4, 0).


In [101]:
np.random.sample(2) # returns 2 values in the half open interval `[0.0,1.0]`

array([0.07103606, 0.0871293 ])

***
## Random integers from the Discrete Uniform Distribution

### 1. The **`numpy.random.randint`** function.  

[Back to top](#toc)

Next I look at the [numpy.random.randint()](https://docs.scipy.org/doc/numpy-1.16.1/reference/generated/numpy.random.randint.html#numpy-random-randint) function which will return random integers from the **discrete uniform distribution** in the interval from low (inclusive) to high (exclusive). ($[low, high)$) 

**`numpy.random.randint()`** is used to generate an array of random integers. 
You must specify how many integers to be generated by providing a size parameter. You can also specify the range from which the random integers will be generated.

There are four possible parameters you can give to this function but at least one is required. Size is the key word argument here which is used to specify how many random numbers should be generated.
When only one parameter is supplied, this value is taken to be upper end of the range (exclusive) and a single integer is generated from 0 up to the upper range minus 1 so `np.random.randint(10)` would result in a single integer that could be any integer from 0 up to 9. 

When a second value is supplied to the function, the first valuer is treated as the low range parameter and the second is treated as the high range parameter so `np.random.randint(5,10)` would output a single integer between 5 inclusive and 9.

The first two arguments relate to the range of values that could be drawn where low is the lowest integer to draw from the distribution, high is the integer after the last possible integer that could be drawn. The next numeric parameter is for the size of the resulting array. This can be a single integer or a tuple of integers for higher dimensions. This will determine the shape and size of the output. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn.

If an argument is provides for the size, then a  size-shaped array of random integers from the appropriate distribution will be returned.

The last possible argument is an optional `dtype` parameter which determines the dtype of the integers in the resulting array. This is not always required as the default value is `np.int` 

The `numpy.random.random_integers` function is similar to `numpy.random.randint` but the `numpy.random.random_integers` function is now deprecated. `numpy.random.random_integers` had a closed interval [low, high] with 1 being the lowest value if high is omitted and was used to generate uniformly distributed discrete non-integers.



### compared to random.randint() function in base python

random integer values can be generated using the `randint()` function of the random package. 
`random.randint(a, b)` returns a random integer N such that a <= N <= b.
`random.randint` takes two arguments, a and b where a is the start of the range and b is the end of the range for the values that are generated. The values are generated from a uniform distribution.


In [4]:
x = np.random.randint(10, size=(2,2))
arrayinfo(x)

x = np.random.randint(5,10,3)
arrayinfo(x)

x = np.random.randint(5,10,(3,2))
arrayinfo(x)

x = np.random.randint(5,10,(2,3))
arrayinfo(x)


 This array is a 2 dimensional array, with a(2, 2) shape and the array has a total number of 4 int64 elements


array([[2, 8],
       [3, 8]])


 This array is a 1 dimensional array, with a(3,) shape and the array has a total number of 3 int64 elements


array([8, 7, 5])


 This array is a 2 dimensional array, with a(3, 2) shape and the array has a total number of 6 int64 elements


array([[5, 9],
       [8, 6],
       [5, 6]])


 This array is a 2 dimensional array, with a(2, 3) shape and the array has a total number of 6 int64 elements


array([[6, 7, 6],
       [5, 9, 6]])

In [5]:
x = np.random.randint(5,10,(2,3,4))
arrayinfo(x)

np.random.randint(5,10)
np.random.randint(5,10,2)



 This array is a 3 dimensional array, with a(2, 3, 4) shape and the array has a total number of 24 int64 elements


array([[[8, 8, 9, 5],
        [7, 5, 8, 9],
        [8, 5, 8, 8]],

       [[7, 9, 5, 6],
        [8, 9, 5, 7],
        [9, 8, 5, 6]]])

8

array([9, 6])

In [7]:
x = np.random.randint(5, size=10)  # a one dimensional array
arrayinfo(x)


 This array is a 1 dimensional array, with a(10,) shape and the array has a total number of 10 int64 elements


array([0, 1, 4, 1, 2, 1, 4, 3, 1, 3])

In [8]:
x = np.random.randint(5, size=(2, 4)) # Generate a 2 x 4 array of integers between 0 and 4, inclusive:
arrayinfo(x)

x = np.random.randint(5, size=(2, 3, 4)) # Generate a 3 dimensional array of integers
arrayinfo(x)

x = np.random.randint(5, size=(2, 3, 4,5)) # Generate a 4 dimensional array of integers
arrayinfo(x)

#np.random.random_integers(5)
np.random.randint(1, 5 + 1)
# DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead


 This array is a 2 dimensional array, with a(2, 4) shape and the array has a total number of 8 int64 elements


array([[3, 0, 3, 4],
       [2, 1, 0, 3]])


 This array is a 3 dimensional array, with a(2, 3, 4) shape and the array has a total number of 24 int64 elements


array([[[3, 1, 1, 1],
        [3, 2, 2, 1],
        [1, 2, 3, 2]],

       [[3, 1, 3, 3],
        [1, 3, 0, 3],
        [2, 3, 0, 3]]])


 This array is a 4 dimensional array, with a(2, 3, 4, 5) shape and the array has a total number of 120 int64 elements


array([[[[1, 1, 2, 3, 2],
         [0, 3, 1, 4, 4],
         [0, 1, 2, 0, 1],
         [2, 4, 2, 4, 4]],

        [[3, 1, 2, 4, 4],
         [1, 0, 3, 1, 2],
         [1, 3, 2, 1, 4],
         [0, 2, 2, 0, 4]],

        [[2, 3, 0, 3, 4],
         [2, 3, 1, 0, 1],
         [2, 3, 1, 3, 2],
         [3, 2, 0, 0, 0]]],


       [[[0, 4, 3, 1, 1],
         [4, 0, 0, 0, 1],
         [4, 1, 0, 0, 2],
         [0, 4, 3, 3, 3]],

        [[2, 3, 3, 4, 1],
         [1, 0, 2, 4, 0],
         [4, 1, 1, 0, 2],
         [3, 0, 2, 1, 1]],

        [[3, 1, 4, 2, 1],
         [4, 4, 2, 0, 1],
         [2, 4, 2, 1, 2],
         [4, 0, 1, 3, 0]]]])

2

`random_integers` was similar to randint, only for the closed interval [low, high], and 1 is the lowest value if high is omitted. In particular, this other one is the one to use to generate uniformly distributed discrete non-integers.
This has now been deprecated. come back to this

#### compared to python's random.randint

Here I will write a loop to generate a sequence of random integers using the base python `random.randint` function.


In [9]:
import random  # import random module
myseq =[]  # create a list to hold the sequence of random numbers
for i in range(10):  ## use a loop to generate a sequence of random numbers
    random_integer = random.randint(0,10) # lower bound a is 0, upper bound b is 10
    myseq.append(random_integer) # append the new element of the sequence to the list
print(myseq) # return the lis    
print(*myseq, sep = ", ") # return the list without the brackets. 

[0, 4, 5, 1, 7, 5, 4, 6, 1, 8]
0, 4, 5, 1, 7, 5, 4, 6, 1, 8


In [10]:
np.random.randint(10,size =10)

array([5, 1, 4, 2, 4, 6, 7, 2, 7, 0])

In [43]:
np.random.randint

<function RandomState.randint>

***
# numpy.random.choice
[numpy.random.choice(a, size=None, replace=True, p=None)](https://numpy.org/doc/1.16/reference/generated/numpy.random.choice.html#numpy-random-choice) generates a random sample from a given 1-D array

The `numpy.random.choice` function is different to the other numpy.random simple random data functions it that it is used to generate a random sample of elements from the elements of a one-dimensional array whereas the simple random data function I looked at above are used to generate random numbers.

To use this function you must provide the array as an argument or else an integer with which to create an array using the `np.arange` function. 

The sample returned could be a single value or an ndarray of values. By providing a size parameter, more than one value is sampled.

The function defaults to using the 'with replacement' sampling method. You can specify that the random sample is without replacement so that the same element cannot be chosen again.

If you don't provide the probabilities for each element of the input array the function will just assume a uniform distribution over all the elements where each elements is equally likely to be chosen. By providing the `p` probabilites, a non-uniform random sample is generated. The number of probabilities should equal the size parameter and the probabilities must sum to 1.0, otherwise an error results.

The `numpy.random.choice` function can also be used on an array of elements other than integers. (This is similar to the `choice` function in the python random module which randomly chooses items from a provided list.)


In [59]:
np.random.choice(10) # select a single element from an array created from np.arange(10)
np.random.choice(5, 3)  # select 3 elements from an array of integers from 0 up to but not including 5
np.random.choice(100, 12) #  select 12 elements from an array from 0 to 99 inclusive.

8

array([2, 1, 4])

array([43, 17,  2, 81, 24, 71, 60, 63, 69, 16, 56, 87])

Note that `np.random.choice()` will result in a *TypeError: choice() takes at least 1 positional argument (0 given)* if not argument is provided.

In [62]:
np.random.choice(5, 4, p=[0.2, 0.1, 0.3, 0.1, 0.3]) ## select 4 elements from integers from 0 to 5 exlusive, with probabilities specified for each element
np.random.choice(5, 4, p=[0.2, 0.1, 0.3, 0.1, 0.3])
np.random.choice(5, 4, p=[0.2, 0.1, 0.3, 0.1, 0.3])
np.random.choice(5, 4, p=[0.2, 0.1, 0.3, 0.1, 0.3])
np.random.choice(5, 4, p=[0.2, 0.1, 0.3, 0.1, 0.3])
np.random.choice(5, 4, p=[0.2, 0.1, 0.3, 0.1, 0.3])

array([1, 4, 2, 2])

array([2, 0, 2, 1])

array([3, 4, 1, 3])

array([3, 2, 2, 4])

array([3, 4, 0, 3])

array([2, 0, 4, 4])

In [ ]:
np.random.choice(['a','b','c','d','e','f'], 5, p=[0.2, 0.15, 0.15, 0.3, 0.1, 0.1]) # selecting from an array of non-integers

In [ ]:
np.random.choice(['a','b','c','d','e','f'], 5, p=[0.2, 0.15, 0.15, 0.3, 0.1, 0.1], replace = False)

The python `random` module also has a `choice()` function which is used to randomly select items from a list.
[random.choice](https://docs.python.org/3/library/random.html#functions-for-sequences) returns a random element from a sequence. 

In [68]:
import random
random.choice(['win', 'lose', 'draw']) 
np.random.choice(['win', 'lose', 'draw']) 

'draw'

'win'

## RandomState

In [49]:
np.random.rand
np.random.randn
np.random.randint
np.random.random_sample
np.random.random
np.random.ranf
np.random.sample
np.random.choice
np.random.bytes

<function RandomState.rand>

<function RandomState.randn>

<function RandomState.randint>

<function RandomState.random_sample>

<function RandomState.random_sample>

<function RandomState.random_sample>

<function RandomState.random_sample>

<function RandomState.choice>

<function RandomState.bytes>

<a id='task2.2'></a>
## 2.1 Permutations functions

[Back to top](#toc)

Explain the use of the “Permutations” functions. 

There are two permutations functions in the numpy random sampling package. (numpy.random)

- shuffle(x) to Modify a sequence in-place by shuffling its contents.
- permutation(x) to Randomly permute a sequence, or return a permuted range.

The numpy`shuffle` function shuffles a sequence in place so that the sequence provided to it is actually shuffled and not just a copy of the sequence.

### numpy.random.shuffle
`numpy.random.shuffle(x)` is used to modify a sequence in-place by shuffling its contents.

This function is used to shuffle an numpy array in-place. The contents of the numpy array is shuffled so that the contents are still the same but in a different order.

>This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same.


In [ ]:
import numpy as np

In [ ]:
arr = np.arange(20)  # the original array
arr
np.random.shuffle(arr) ## the shuffled array
arr


>This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same.

In [ ]:
arr = np.arange(12).reshape((3, 4))  ## create a 3 by 4 two-dimensional array
arr
arr.ndim
arr.shape
np.random.shuffle(arr)
arr

### numpy.random.permutation


Randomly permute a sequence, or return a permuted range.

If x is a multi-dimensional array, it is only shuffled along its first index.

Parameters:	
x : int or array_like
If x is an integer, randomly permute np.arange(x). If x is an array, make a copy and shuffle the elements randomly.
Returns:	
out : ndarray




In [ ]:
np.random.permutation(10)


In [ ]:
np.random.permutation([1, 4, 9, 12, 15])

In [ ]:
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)


The python `random` package also has a function for shuffling a list of items in place.
`random.shuffle`.

[Back to top](#toc)

<a id='task3'></a>
# 3. Explain the use and purpose of at least five “Distributions” functions.

[Back to top](#toc)  


<a id='distributions'></a>
While the functions outlined under the [Simple random data](#Simplerandomdata) section of the [Random sampling (numpy.random)](https://numpy.org/doc/1.16/reference/routines.random.html#simple-random-data) are noted as functions that return random values in a given shape, the functions under the [Distributions](https://numpy.org/doc/1.16/reference/routines.random.html#distributions) section are noted as functions that draw samples from a particular probability distribution. 
## Distributions
- `beta(a, b[, size])` 	Draw samples from a Beta distribution.
- `binomial(n, p[, size])` 	Draw samples from a binomial distribution.
- `chisquare(df[, size])` 	Draw samples from a chi-square distribution.
- `dirichlet(alpha[, size])` 	Draw samples from the Dirichlet distribution.
- `exponential([scale, size])` 	Draw samples from an exponential distribution.
- `f(dfnum, dfden[, size])` 	Draw samples from an F distribution.
- `gamma(shape[, scale, size])`	Draw samples from a Gamma distribution.
- `geometric(p[, size])`	Draw samples from the geometric distribution.
- `gumbel([loc, scale, size])`	Draw samples from a Gumbel distribution.
- `hypergeometric(ngood, nbad, nsample[, size])`	Draw samples from a Hypergeometric distribution.
- `laplace([loc, scale, size])`	Draw samples from the Laplace or double exponential distribution with specified location (or mean) and scale (decay).
- `logistic([loc, scale, size])`	Draw samples from a logistic distribution.
- `lognormal([mean, sigma, size])`	Draw samples from a log-normal distribution.
- `logseries(p[, size])`	Draw samples from a logarithmic series distribution.
- `multinomial(n, pvals[, size])`	Draw samples from a multinomial distribution.
- `multivariate_normal(mean, cov[, size, …)`	Draw random samples from a multivariate normal distribution.
- `negative_binomial(n, p[, size])`	Draw samples from a negative binomial distribution.
- `noncentral_chisquare(df, nonc[, size])`	Draw samples from a noncentral chi-square distribution.
- `noncentral_f(dfnum, dfden, nonc[, size])`	Draw samples from the noncentral F distribution.
- `normal([loc, scale, size])`	Draw random samples from a normal (Gaussian) distribution.
- `pareto(a[, size])`	Draw samples from a Pareto II or Lomax distribution with specified shape.
- `poisson([lam, size])`	Draw samples from a Poisson distribution.
- `power(a[, size])`	Draws samples in [0, 1] from a power distribution with positive exponent a - 1.
- `rayleigh([scale, size])`	Draw samples from a Rayleigh distribution.
- `standard_cauchy([size])`	Draw samples from a standard Cauchy distribution with mode = 0.
- `standard_exponential([size])`	Draw samples from the standard exponential distribution.
- `standard_gamma(shape[, size])`	Draw samples from a standard Gamma distribution.
- `standard_normal([size])`	Draw samples from a standard Normal distribution (mean=0, stdev=1).
- `standard_t(df[, size])`	Draw samples from a standard Student’s t distribution with df degrees of freedom.
- `triangular(left, mode, right[, size])`	Draw samples from the triangular distribution over the interval [left, right].
- `uniform([low, high, size])`	Draw samples from a uniform distribution.
- `vonmises(mu, kappa[, size])`	Draw samples from a von Mises distribution.
- `wald(mean, scale[, size])`	Draw samples from a Wald, or inverse Gaussian, distribution.
- `weibull(a[, size])`	Draw samples from a Weibull distribution.
- `zipf(a[, size])`	Draw samples from a Zipf distribution.

Random numbers can be drawn from different probability distributions. 

use some plots and statistics here to show the differences between the types of random numbers that would be generated from the different probability distributions.)

All these functions just generate different random numbers according to different probabilities over different intervals.
Pick a handful and show the differences between them. Need to have a programming knowledge of them.



What are Distributions. 

<img src="/Distributions.png" width="400" alt="NumPy Distributions" />

## Numpy Random Distribution Functions. 

***
Here I am just going through some  of my old notes from a statistics college course to refresh myself!
Also referring to [Mathworld.wolfram.com](http://mathworld.wolfram.com), [statttrk.com](https://stattrek.com/statistics/dictionary.aspx?definition=random%20variable), [Wikipedia](https://en.wikipedia.org/wiki/Normal_distribution) and other sources.

***

**Probability** is a mathematical expression of uncertainty of the chance of a random variable taking on particular values.
According to [wolfram mathworld](http://mathworld.wolfram.com/Probability.html), **probability**
>is the branch of mathematics that studies the possible outcomes of given events together with the outcomes' relative likelihoods and distributions. In common usage, the word "probability" is used to mean the chance that a particular event (or set of events) will occur expressed on a linear scale from 0 (impossibility) to 1 (certainty), also expressed as a percentage between 0 and 100%. The analysis of events governed by probability is called statistics.

A **random variable** is a variable that assumes numerical values associated with the random outcome of an experiment where one (and only one) numerical value is assigned to each sample point. A random variable is any quantity that is assumed to have a probability distribution.
A random variable is **discrete** if its set of possible values is a collection of isolated points on the number line. It is **continuous** if its set of possible values is an entire interval on the number line.
Discrete random variables almost always come from counting while continuous random variables mostly come from measurement.

A **probability distribution** is a complete description of a random variable specifying all possible values it can have and the probability associated with each one.
A probability distribution is a table or an equation that links each possible value that a random variable can assume with its probability of occurrence. [probability distribution definition](https://stattrek.com/probability/probability-distribution.aspx?tutorial=prob)

The probability distribution of a discrete random variable is often known as a probability function or a probability mass function, it can be displayed as a graph, table or mathematical formula that specifies the probability associated with each possible value the random variable can assume.
A probability distribution for a continuous random variable x is specified by a mathematical function f(x) called a probability density function, a frequency function or a probability distribution.

**Random Numbers**  

Random numbers can be drawn from different probability distributions. The NumPy Random module has many functions that can be used to generate random numbers from various probability distributions over different intervals. Below I will go through several of these numpy.random distribution functions and use plots and statistics to show the differences between the types of random numbers that would be generated from the different probability distributions.




learning latex...
$e^{i\pi} + 1 = 0$
$$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$$

## Normal Distribution Function
- `normal([loc, scale, size])` Draw random samples from a normal (Gaussian) distribution.

The [numpy.random.normal](https://numpy.org/doc/1.16/reference/generated/numpy.random.normal.html#numpy-random-normal) function is used to draw random samples from a normal (Gaussian) distribution. 

>The probability density function of the normal distribution, first derived by De Moivre and 200 years later by both Gauss and Laplace independently, is often called the bell curve because of its characteristic shape .

>The normal distributions occurs often in nature. For example, it describes the commonly occurring distribution of samples influenced by a large number of tiny, random disturbances, each with its own unique distribution.


[stattrek](https://stattrek.com/statistics/dictionary.aspx?definition=random%20variable) defines the normal distribution as a probability distribution that associates the normal random variable X with a cumulative probability.

The normal distribution is also known as the Gaussian Distribution or the Bell Curve.

According to "The Art of Statistics", The normal distribution can be expected to occur for phenomena that are driven by large numbers of small influences. 
When all the small influences are added up you get a normal distribution.

[numpy.random.normal(loc=0.0, scale=1.0, size=None)](https://numpy.org/doc/1.16/reference/generated/numpy.random.normal.html#numpy-random-normal) depends on two factors, the mean and the standard deviation. Normal distributions resemble a symmetric bell-shaped curve when plotted.

The mean of the distribution determines the location of the center of the graph. The standard deviation determines the height and shape or spread of the graph. When the standard deviation is large, the curve is short and wide and when the standard deviation is small, the curve is tall and narrow. 

A normal distribution has a bell-shaped density curve described by its mean μ and standard deviation σ. The density curve is symmetrical and centered about its mean. The spread is determined by the standard deviation. Data points near the mean occur more frequently than data points that are far from the mean. 



In [ ]:
# using the example from the documentation to start with
import numpy as np
mu, sigma = 0, 0.1 # mean and standard deviation
x = np.random.normal(mu, sigma, 10000)
#plt.hist(x)


sns.distplot(x);  # using seaborn

Centred around the mean of 0 and 

In [ ]:
# changing some of the parameters and seeing what happens
mu, sigma = 10, 1 # mean and standard deviation
x = np.random.normal(mu, sigma, 10000)
sns.distplot(x);  # using seaborn



numpy.random.normal()

In [ ]:
# changing some of the parameters again and seeing what happens
mu, sigma = 100, 10 # mean and standard deviation
x = np.random.normal(mu, sigma, 10000)
sns.distplot(x);  # using seaborn



In [ ]:
import numpy as np

np.random.normal()

<a id='standard_normal'></a>
## The Standard Normal Distribution function

The [standard normal distribution](https://stattrek.com/statistics/dictionary.aspx?definition=random%20variable) is a special case of the normal distribution. 
>It is the distribution that occurs when a normal random variable has a mean of zero and a standard deviation of one.  The normal random variable of a standard normal distribution is called a standard score or a z score. Every normal random variable X can be transformed into a z score

The [numpy.random.standard_normal](https://numpy.org/doc/1.16/reference/generated/numpy.random.standard_normal.html#numpy-random-standard-normal) is used to draw samples from a standard Normal distribution with a mean of 0 and a standard deviation of 1.

`numpy.random.standard_normal(size=None)`
Draw samples from a standard Normal distribution (mean=0, stdev=1).

Parameters:
size : int or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.


In [ ]:
# using the example from the documentation to start with
s = np.random.standard_normal(8000)
s

sns.distplot(s)





In [ ]:
np.random.standard_normal()

## The Uniform distribution

A uniform distribution, sometimes also known as a rectangular distribution, is a distribution that has constant probability.

#### numpy.random.uniform function.
Note that this is related to the `random.rand` function earlier.


In [ ]:
x = np.random.uniform(-1,0,1000) 
sns.distplot(x);  # using seaborn

low is the lower bound of the interval, high is the upper bound of the interval. Note that the lower bound is included but the upper bound of 1 is not included.
When you put the bigger number before the smaller number it seems to just take the bigger number as the upper bound and the smaller number as the lower bound. 
Try and put low before high. 

rand only gives you random uniform numbers between 0 and 1 whereas this uniform function will give you numbers in any range.

In [ ]:
np.random.uniform(10,9,10) 


In [ ]:
x = np.random.uniform(-100,100,10000) 
sns.distplot(x);  # using seaborn

## The Binomial distribution.


### numpy.random.binomial

http://mathworld.wolfram.com/BinomialDistribution.html

The `numpy.random.binomial` function is used to draw samples from a binomial distribution. 


One of the most important probability distributions for discrete random variables is the binomial distribution.

The [binomial distribution](http://mathworld.wolfram.com/BinomialDistribution.html) gives the discrete probability distribution P_p(n|N) of obtaining exactly n successes out of N Bernoulli trials (where the result of each Bernoulli trial is true with probability p and false with probability q=1-p). 






>numpy.random.binomial(n, p, size=None)
Draw samples from a binomial distribution.

>Samples are drawn from a binomial distribution with specified parameters, n trials and p probability of success where n an integer >= 0 and p is in the interval [0,1]. (n may be input as a float, but it is truncated to an integer in use)

>Parameters:	
n : int or array_like of ints
Parameter of the distribution, >= 0. Floats are also accepted, but they will be truncated to integers.
p : float or array_like of floats
Parameter of the distribution, >= 0 and <=1.
size : int or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if n and p are both scalars. Otherwise, np.broadcast(n, p).size samples are drawn.
Returns:	
out : ndarray or scalar
Drawn samples from the parameterized binomial distribution, where each sample is equal to the number of successes over the n trials.

In [ ]:
n, p = 100, .5  # number of trials, probability of each trial
x = np.random.binomial(n, p, 10000)
sns.distplot(x);  # using seaborn

In [ ]:
n, p = 10, .5  # number of trials, probability of each trial
s = np.random.binomial(n, p, 10000)
plt.hist(s)

<a id='task4'></a>
# 4. Explain the use of seeds in generating pseudorandom numbers.
[Back to top](#toc)  

See the section https://docs.scipy.org/doc/numpy-1.16.0/reference/routines.random.html#random-generator

Random Generator.
- `RandomState([seed])`
- `seed([seed])`
-` get_state()`  is used to capture the state of random at any time, returns a tuple representing the internal state of the generator.   
- `set_state(state)`  sets the internal state of the generator from the tuple and is used if for any reason you want to manually reset the internal state of the "Mersenne Twister"

The tuple returned from `getstate` can be passed to `setstate` method to duplicate the generation at that moment.


<a id='task4'></a>
# 4. Explain the use of seeds in generating pseudorandom numbers.
[Back to top](#toc)  

### Pseudo-random number generators (PRNG's) and seeds

***
A **seed** is a number that is used to initialise a pseudorandom number generator. By setting the seed, the original seed is ignored and numbers will be generated in a pseudorandom manner. If you reinitialise a random number generator with the same seed then the same sequence of numbers will be produced. 

According to [statisticshowto](https://www.statisticshowto.datasciencecentral.com/random-seed-definition/), a random seed specifies the start point when a computer generates a random number. The random seed can be any number but it usually comes from seconds on the computer system's clock which counts in seconds from January 1, 1970.  (known as Unix time). This ensures that the same random sequence won't be repeated unless you actually want it to. 

Computer programs generate random numbers in a *deterministic* way - that is they follow a very particular set of rules to generate the random numbers, which means therefore that the random numbers are not actually random at all!
Randomness is instead being imitated. The algorithms behind computer number generation are based on patterns which generate numbers that follow particular **probability distributions**. Setting a seed will produce the same sequence of random numbers each time. 

https://pynative.com/python-random-seed/
>Random number or data generated by Python’s random module is not truly random, it is pseudo-random(it is PRNG), i.e. deterministic. It produces the numbers from some value. This value is nothing but a seed value. i.e. The random module uses the seed value as a base to generate a random number.

>Generally, the seed value is the previous number generated by the generator. However, When the first time you use the random generator, there is no previous value. So by-default current system time is used as a seed value.
 

There are many different ways to generate pseudo-random numbers. Python uses the **Mersenne Twister** as the core generator. According to [wikipedia](https://en.m.wikipedia.org/wiki/Mersenne_Twister), the Mersenne Twister is  a pseudorandom number generator (PRNG) and is by far the most widely used general-purpose PRNG whose name derives from the fact that its period length is chosen to be a Mersenne prime (a prime number that is one less than a power of two. That is, it is a prime number of the form Mn = 2n − 1 for some integer n.).

There are times when you may wish to recreate the exact same sequence of random numbers.  Pseudo random number generators can be **seeded** which makes them **deterministic** and the series of random values can therefore be exactly recreated. A seed is an input to the random number generator as the starting point of the process. The computer's system time is usually used for the seed and this is used in an algorithm to generate some (pseudo) random values. If you provide the seed as an input to the process this tells the program not to generate its own random seed at the start from the computer's clock (to the microsecond) but instead use the seed you provide
 

In summary, random (pseudorandom) numbers are drawn from a probability distribution. The numbers generated depend on the *seed* used and are generated according to some deterministic algorithm from that seed. The numbers that are output depend on the algorithm and the input seed.



## using numpy.random.seed function

Numpy random seed function is used to create completely repeatable or reproducible results.
The seed function works with other numpy random functions to create particular types of random numbers, such as numbers from various probability distributions. 
If a numpy random function is used together with a particular seed, then the very same set of random numbers can be generated again. 

The seed value is the input to the numpy random seed function. You **seed** or set the set of the prng. If you run the same function again you will get the same output. The code will produce the exact same output if the same seed is used with the same function, using the same parameters.

To get the same random sample of elements from a array of numbers then you also use the numpy random seed function. 

Prngs are algorithms for producing numbers that appear random. The seed is the starting point for the algorithm. 
Different numbers used as the seed will produce a different set of pseudo random numbers from the same algorithm as they have a different starting point. If the starting point is the same and the steps in the algorithm are the same, then the outputs will be the same. 
Any integer can be used (see the documents for exact range) as the input seed. If a different seed is used, a different set of random numbers are generated but if the same number is used, the same sequence is generated. The same principle applies for randomly sampling from a set or array of numbers.
If you don't explicitly set the seed, one will be set automatically for you using the system time.


Any NumPy random function that is executed with the same seed will produce the exact same result and this will ensure reproducibility.


***

From the documentation:

#### numpy.random.seed

`numpy.random.seed(seed=None)`  # Seed the generator.

This method is called when `RandomState` is initialized. It can be called again to re-seed the generator. 

Parameters: 
seed : int or 1-d array_like, optional
Seed for RandomState. Must be convertible to 32 bit unsigned integers.

#### numpy.random.RandomState

class **numpy.random.RandomState(seed=None)** Container for the Mersenne Twister pseudo-random number generator.

`RandomState` exposes a number of methods for generating random numbers drawn from a variety of probability distributions. In addition to the distribution-specific arguments, each method takes a keyword argument size that defaults to None. If size is None, then a single value is generated and returned. If size is an integer, then a 1-D array filled with generated values is returned. If size is a tuple, then an array with that shape is filled and returned.


Parameters:
seed : {None, int, array_like}, optional
Random seed used to initialize the pseudo-random number generator. Can be any integer between 0 and `2**32 - 1` inclusive, an array (or other sequence) of such integers, or None (the default). If seed is None, then RandomState will try to read data from `/dev/urandom` (or the Windows analogue) if available or seed from the clock otherwise.


In [ ]:
#np.random.get_state()

#### Here I will demonstrate using the numpy random functions, with and without setting the seed of the random number generator.

When I use the `random.seed` method with any integer (in the accepatable range) then the same sequence of random numbers will be generated when this number is used to seed the generator again. It doesn't matter what number is used as the seed as long as the same number is used as a seed again when you want to generate the exact same sequence. If a different seed is used, then a different sequence of random numbers will be generated. The output of a random function will depend on the seed used and the algorithm the function uses. 
Without explicitly specifying a seed, a seed is generated from the system clock. If you don't specify a seed it would be extremely difficult to reprodce the same sequence again. As the default seed is set from the computer systems internal clock (to the millisecond) the seed will change every moment that you use a numpy random function.

As the documentation mentions above, the `numpy.random.seed` method is called when `RandomState` is initialized. It can be called again to re-seed the generator.

Using a seed with random sampling makes sense if you want reproducible outputs.

##### Generate random numbers with and without seeding the generator

In [ ]:

np.random.rand() # generate a random float between 0 and 1 without using a seed
np.random.rand() # # generate another random float between 0 and 1 without using a seed



In [ ]:
np.random.seed(123)  # using a seed with any integer value between 0 and 2**32 -1
np.random.rand() # generate a random float between 0 and 1 without using a seed
np.random.seed(123) ## using same seed
np.random.rand() # produces the same results

In [ ]:
2**32 - 1

In [ ]:
np.random.seed(456)
np.random.randint(0,100,10)

In [ ]:
np.random.seed(456)
myarray = np.random.randint(0,100,20)
myarray

##### Random sampling from an array with and without seeding the generator.

In [ ]:
np.random.seed(21)  # set the seed of the random number generator
np.random.choice(myarray,4)  # random sample 4 elements from array using a seed
np.random.seed(21)
np.random.choice(myarray,4)

In [ ]:
np.random.seed(12)
np.random.choice(['a','b','c','d','e','f'], 3, p=[0.2, 0.15, 0.15, 0.3, 0.1, 0.1], replace = False)
np.random.seed(12)
np.random.choice(['a','b','c','d','e','f'], 3, p=[0.2, 0.15, 0.15, 0.3, 0.1, 0.1], replace = False)

In [ ]:
np.random.seed(12)
np.random.choice(['s','a','u','c','e','m','n'], 3, p=[0.14, 0.28, 0.1, 0.16,0.14, 0.1, 0.08], replace = False)

There are various methods of sampling random numbers.
With replacement means the number drawn would be placed back in and could be selected again. 
No replacement means that once a number is chosen, it can no longer be chosen again in the same sample as it is not placed back in the pot. In this way there will be no duplicates.
it cannot be selected again in the same sample. It is no longer available and this means there will be no possibility of duplicates.


Pythons built-in `random` module implements pseudo-random numbers for various distributions. See [python docs/random library](https://docs.python.org/3/library/random.html). However this built-in`random` module only samples one value at a time and probably uses loops to generate sequences of random numbers.   
`numpy.random` provides functions that can efficiently generate arrays of sample values from various probability distributions rather than one value at a time. It is much much faster and more efficient.

<a id='references'></a>
## References
- Python for Data Analysis - Chapter 4 NumPy Basics: Arrays and Vectorised Computation by Wes McKinney
- [Python Data Science Handbook by Jake VanderPlas ](https://jakevdp.github.io/PythonDataScienceHandbook/) 
- [Jake VanderPlas Website](http://vanderplas.com)
- [numpy quickstart tutorial](https://numpy.org/devdocs/user/quickstart.html)
- [NumPy random module](https://numpy.org/devdocs/reference/random/index.html?highlight=random#module-numpy.random), 
- [python - random library](https://docs.python.org/3/library/random.html#module-random)
- Section 4.6 of Python for Data Analysis by Wes McKinney
- [GitHub Flavoured Markdown](https://github.github.com/gfm/)
- [Jupyter Notebook documentation](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#basic-workflow)
- [Jupyter Notebook Tips, Tricks, and Shortcuts](https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/)
- [python random docs](https://docs.python.org/3/library/random.html#module-random)
- [realpython tutorial on random data](https://realpython.com/python-random/)
- [A Concrete Introduction to Probability (using Python) by Peter Norvig](https://nbviewer.jupyter.org/url/norvig.com/ipython/Probability.ipynb) 
Note: I have not actually read through this in detail yet. It is linked in the python random module documentation.
- [wolfram mathworld](http://mathworld.wolfram.com/topics/StatisticalDistributions.html)
- [stattrek](https://stattrek.com)

-[LaTeX equations in Jupyter](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html#LaTeX-equations)


[Back to top](#toc)

In [ ]:
import random
random.randrange(300,500)